config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
  resources :cocktails, only: [:show, :index, :new, :create ] do
    resources :doses, only: [ :create, :new ]
  end
  resources :doses, only: [:destroy]
  resources :ingredients, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name, uniqueness: true, presence: true, allow_blank: false

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, except: [:destroy]

  def new
    @dose = Dose.new
    @dose.cocktail
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @ingredients = Ingredient.all
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name, placeholder: "Your favorite drink" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<body style="background-color: #BEF7EB">
  <h1 class="text-center">Your cocktail list</h1>
  <div class="container">
    <div class="text-center padded"><%= cl_image_tag "Jamaican_Coffee", height: 500, width: 600, crop: :fill %>
    </div>

    <div class="text-center padded">
      <div class="row">
        <%= link_to "Create a cocktail", new_cocktail_path, class: 'btn btn-primary btn-medium' %>
        <% @cocktails.each do |cocktail| %>
          <p><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/cocktails/new.html.erb
<body style="background-color: #E0F9F9">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Cocktail</h1>
      <%= render 'form' %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<body style="background-color: #E0F9F9">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

      <ul class="list-unstyled">
        <% @cocktail.doses.each do |dose| %>
          <li><%= link_to dose.ingredient.name, ingredient_path(dose.ingredient) %> : <%= dose.description %>
            <%= link_to "<i class='fa fa-close'></i>".html_safe, dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></li>
        <% end %>
      </ul>

      <h2 class="text-center">Add a Dose</h2>

      <% if @dose.errors.any? %>
        <ul>
          <% @dose.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.input :description %>
        <%= f.input :ingredient_id, collection: @ingredients %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>

      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<h1>dose</h1>

app/views/doses/show.html.erb
show.html.erb

<h1>Cocktails featuring <%= @ingredient.name %>: </h1>

<ul>
  <% @ingredient.cocktails.each do |cocktail| %>
    <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= cloudinary_js_config %>
  </body>
</html>